# Generated by Django 4.0.1 on 2022-01-19 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('D_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('D_name', models.CharField(max_length=100)),
                ('D_email', models.CharField(max_length=100)),
                ('D_age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('D_number', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('P_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=100)),
                ('P_email', models.CharField(max_length=100)),
                ('P_age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('P_number', models.DecimalField(decimal_places=0, max_digits=3)),
                ('P_medicalrecord', models.CharField(max_length=200)),
                ('D_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('Pr_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('Pr_detail', models.CharField(max_length=100)),
                ('Pr_medicalrecord', models.CharField(max_length=100)),
                ('D_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.doctor')),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('m_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=100)),
                ('m_price', models.DecimalField(decimal_places=0, max_digits=4)),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('B_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('B_total', models.DecimalField(decimal_places=0, max_digits=6)),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('app_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('app_purpose', models.CharField(max_length=500)),
                ('app_request', models.CharField(default='', max_length=100)),
                ('app_link', models.CharField(default='', max_length=100)),
                ('D_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.doctor')),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
    ]
